# Detekt configuration file
autoCorrect: true
build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 1

processors:
  active: true
  exclude:
    - 'DetektProgressListener'
    - 'KtFileCountProcessor'
    - 'PackageCountProcessor'
    - 'ClassCountProcessor'
    - 'FunctionCountProcessor'
    - 'PropertyCountProcessor'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'BuildFailureReport'
    - 'FileBasedFindingsReport'
