[versions]
# CORE BUILD PLUGINS - Corrected to a stable version
agp = "8.4.1"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
hilt = "2.51.1" # Matched to stable Hilt version
googleServicesPlugin = "4.4.2"
navigationSafeargs = "2.7.7"
composeCompiler = "1.5.8" # Compatible with Kotlin 1.9.22
composeBom = "2024.05.00"

# LIBRARIES
androidxActivity = "1.9.0"
androidxAppcompat = "1.7.0"
androidxCore = "1.13.1"
androidxLifecycle = "2.8.1"
androidxRoom = "2.6.1"
androidxWorkRuntimeKtx = "2.9.0"
androidxDatastorePreferences = "1.1.1"
# Aligned all Netty versions to prevent runtime crashes
netty = "4.1.112.Final"
coroutines = "1.8.0"
serializationJson = "1.6.3"
serializationXml = "0.9.1"
retrofit = "2.9.0"
retrofitKotlinxSerializationConverter = "1.0.0"
okhttp = "4.12.0"
googleMaterial = "1.12.0"
firebaseBom = "33.0.0"
googleCloudBom = "26.34.0"
timber = "5.0.1"
coil = "2.6.0"
accompanist = "0.34.0"
desugarJdkLibs = "2.0.4"

# Xposed - Using standard API level for version
xposedApi = "82"
xposedHiddenapibypass = "4.3" # Check for the actual artifact version

# TESTING
junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
androidxEspressoCore = "3.5.1"
mockk = "1.13.11"
mockitoCore = "5.11.0"
androidxArchCoreTesting = "2.2.0"

[libraries]
# Build Plugins (for root build.gradle.kts)
android-application-plugin = { id = "com.android.application", version.ref = "agp" }
kotlin-android-plugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services-plugin = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
navigation-safeargs-plugin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeargs" }
compose-compiler-plugin = { id = "org.jetbrains.compose", version.ref = "composeCompiler"}

# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.2.0" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version = "1.2.0" }

# Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

# Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
kotlinx-serialization-xml = { group = "io.github.pdvrieze.xmlutil", name = "kotlinx-serialization-xml-jvm", version.ref = "serializationXml" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

# Data & Work
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkRuntimeKtx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePreferences" }

# Networking
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Netty (All versions aligned)
netty-codec-http = { group = "io.netty", name = "netty-codec-http", version.ref = "netty" }
netty-codec-http2 = { group = "io.netty", name = "netty-codec-http2", version.ref = "netty" }
netty-handler = { group = "io.netty", name = "netty-handler", version.ref = "netty" }
netty-common = { group = "io.netty", name = "netty-common", version.ref = "netty" }

# UI Components
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version = "1.1.0-rc01" }
glance-compose = { group = "androidx.glance", name = "glance-material3", version = "1.1.0-rc01" }

# Firebase & Google Cloud
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
google-cloud-bom = { group = "com.google.cloud", name = "libraries-bom", version.ref = "googleCloudBom" }
google-cloud-generativeai = { group = "com.google.cloud.vertexai", name = "vertexai-generative-ai" }

# Xposed
xposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "xposedHiddenapibypass" }

# Other
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version = "3.25.3" }
commons-io = { group = "commons-io", name = "commons-io", version = "2.16.1" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version = "1.78.1" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version = "1.26.2" }
guava = { group = "com.google.guava", name = "guava", version = "33.2.0-android" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[plugins]
# Aliases for plugins for type-safe access in build scripts
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeargs" }
compose-compiler = { id = "org.jetbrains.compose", version.ref = "composeCompiler" }
openapi-generator = { id = "org.openapi.generator" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }