# libs.versions.toml

[versions]
androidGradlePlugin = "8.10.0"
kotlin = "1.9.22"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
jvmTarget = "17"

composeBom = "2024.04.00"
composeCompiler = "1.5.11"

hilt = "2.56.2"
hiltWork = "1.2.0"

firebaseBom = "32.7.0"
firebaseCrashlytics = "2.9.9"
firebasePerformance = "1.4.2"
googleServices = "4.4.1"

ksp = "1.9.22-1.0.17"
navigation = "2.7.7"



googleCloudAiplatform = "2.19.0"
googleApiGrpcAiplatformV1 = "3.64.0"
googleGenerativeAi = "0.4.0"
googleCloudVertexAi = "0.5.0"

okhttp = "4.12.0"
retrofit = "2.9.0"
retrofitConverterGson = "2.9.0"

coil = "2.6.0"
lottie = "6.6.0"

androidxConstraintLayout = "2.1.4"
androidxCoreKtx = "1.12.0"
androidxLifecycleRuntimeKtx = "2.7.0"
androidxLifecycleViewmodelCompose = "2.7.0"
androidxNavigationCompose = "2.7.6"
androidxWorkRuntimeKtx = "2.10.1"

junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
espressoCore = "3.5.1"
composeUiTestJunit4 = "1.6.0"
composeUiTestManifest = "1.6.0"
composeUiTooling = "1.6.0"
composeUiToolingPreview = "1.6.0"


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-performance = { id = "com.google.firebase.firebase-perf-gradle-plugin", version.ref = "firebasePerformance" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinserializationjson = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycleViewmodelCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigationCompose" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkRuntimeKtx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


material = { group = "com.google.android.material", name = "material", version = "1.12.0" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltWork" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.8.1" }


firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-storage = { group = "com.google.firebase", name = "firebase-storage" }

google-cloud-aiplatform = { group = "com.google.cloud", name = "google-cloud-aiplatform", version.ref = "googleCloudAiplatform" }
google-api-grpc-protoGoogleCloudAiplatformV1 = { group = "com.google.api.grpc", name = "proto-google-cloud-aiplatform-v1", version.ref = "googleApiGrpcAiplatformV1" }
google-generative-ai = { group = "com.google.ai.client.generativeai", name = "generative-ai", version.ref = "googleGenerativeAi" }
google-cloud-vertexai = { group = "com.google.cloud.vertexai", name = "vertexai", version.ref = "googleCloudVertexAi" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitConverterGson" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }