[versions]

agp = "8.14.2"

androidxActivity = "1.10.1"
androidxArchCoreTesting = "2.2.0"
androidxCardview = "1.0.0"
# Using the latest stable Compose versions
# Latest stable BOM as of June 2024
androidxComposeBom = "2024.06.00"
# Compatible with Kotlin
androidxComposeCompiler = "1.5.14"
androidxConstraintlayout = "2.2.1"
androidxConstraintlayoutCompose = "1.1.1"
androidxCore = "1.16.0"
androidxAppcompat = "1.7.1"
androidxDatastorePreferences = "1.1.7"
androidxEspressoCore = "3.6.1"
androidxExtJunit = "1.2.1"
androidxHiltNavigationCompose = "1.2.0"
androidxHiltWork = "1.2.0"
androidxLifecycle = "2.9.1"
androidxNavigationCompose = "2.9.0"
androidxRoom = "2.7.1"
# Same as androidxExtJunit, check if this is intended or a typo
androidxTestJunit = "1.2.1"
androidxWorkRuntimeKtx = "2.10.1"
coil = "2.7.0"
desugarJdkLibs = "2.1.5"
firebaseAnalytics = "22.4.0"
firebaseAuth = "23.2.1"
firebaseBom = "33.15.0"
firebaseCrashlytics = "19.4.4"
firebaseCrashlyticsPlugin = "3.0.2"
firebaseFirestore = "25.1.4"
firebaseStorage = "21.0.2"
# Assuming androidx.glance:glance
glance = "1.1.1"
# Latest stable version
googleCloudGenerativeAi = "0.3.2"
# Add Google Cloud BOM for better dependency management
googleCloudBom = "26.28.0"
# Check for latest version and specific artifact if different
googleCloudVertexAi = "1.24.0"
googleMaterial = "1.12.0"
googleServicesPlugin = "4.4.2"
hilt = "2.56.2"
junit = "4.13.2"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
# Version forced in root build.gradle
kotlinxCoroutines = "1.7.3"
# Aligning with kotlinxCoroutines
kotlinxCoroutinesTest = "1.7.3"
# Version forced in root build.gradle
kotlinxSerializationJson = "1.6.3"
# Placeholder, usually it's kotlinx-serialization-json or -protobuf etc.
kotlinxSerializationCore = "1.8.1"
# Using a stable version of kotlinx-serialization-xml

# Stable version that works with Kotlin 1.9.x
kotlinxSerializationXml = "1.6.0"
# Version for Xposed APIs often matches API level
libxposedApi = "82"
# Version for Xposed APIs
libxposedService = "82"
=======

lottieCompose = "6.6.6"
mockitoCore = "5.18.0"
mockk = "1.14.2"
# Retrofit brings its own OkHttp, but good to have a version if used directly
okhttp = "4.12.0"
okhttpLoggingInterceptor = "4.12.0"
# Version forced in root build.gradle
retrofit = "2.9.0"
# Aligning with retrofit
retrofitConverterGson = "2.9.0"
retrofitConverterKotlinxSerialization = "1.0.0"
timber = "5.0.1"
xposedApi = "82"
xposedApiSources = "82"
# These are often just API level, not typical maven artifacts.
xposedArt = "82"
xposedArtSources = "82"
xposedBridge = "82"
xposedBridgeSources = "82"
# Check specific version for this library
xposedHiddenapibypass = "6.1"

# Accompanist - Consider migrating to official Compose APIs if available
# Check for latest or alternatives
accompanistPermissions = "0.37.3"
accompanistSystemuicontroller = "0.36.0"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-arch-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidxCardview" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.3.2" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.8.2" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
# Added based on app/build.gradle.kts
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text"}
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "androidxConstraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastorePreferences" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
# Added based on app/build.gradle.kts
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork"}
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigationCompose" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
# Corrected group
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxExtJunit" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWorkRuntimeKtx" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebaseAnalytics" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
# Removed -ktx as it's not standard for crashlytics artifact
firebase-crashlytics-lib = { group = "com.google.firebase", name = "firebase-crashlytics", version.ref = "firebaseCrashlytics"} # Renamed to avoid conflict with plugin
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestore" }
# Removed -ktx as it's not standard for storage artifact
firebase-storage = { group = "com.google.firebase", name = "firebase-storage", version.ref = "firebaseStorage" }

glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
# Or glance-material, check your specific need
glance-compose = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }

google-cloud-bom = { group = "com.google.cloud", name = "google-cloud-bom", version.ref = "googleCloudBom" }
google-cloud-generativeai = { group = "com.google.cloud", name = "google-cloud-generativeai", version.ref = "googleCloudGenerativeAi"}
# Ensure this is the correct artifact and group
google-cloud-vertexai = { group = "com.google.cloud", name = "google-cloud-vertexai", version.ref = "googleCloudVertexAi" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.7.3" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-play-services = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines"}
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
# Check actual artifact name
kotlinx-serialization-xml = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-xml", version.ref = "kotlinxSerializationXml"}

# Commonly used group/name for this
libxposed-api = { group = "de.robv.android.xposed", name = "api", version.ref = "libxposedApi" }
# Commonly used group/name for this
libxposed-service = { group = "de.robv.android.xposed", name = "service", version.ref = "libxposedService" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockitoCore" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLoggingInterceptor" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version = "2.9.0" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitConverterGson" }
retrofit-converter-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitConverterKotlinxSerialization" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

xposed-api = { group = "local", name = "xposed-api-82", version = "1.0" }
xposed-api-sources = { group = "local", name = "xposed-api-82-sources", version = "1.0" }
xposed-bridge = { group = "local", name = "xposed-bridge-82", version = "1.0" }
xposed-bridge-sources = { group = "local", name = "xposed-bridge-82-sources", version = "1.0" }
# Group and name might vary
xposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version.ref = "xposedHiddenapibypass" }

# Accompanist
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version = "0.37.3" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
# kotlinParcelize = { id = "kotlin-parcelize", version.ref = "kotlin" } # or org.jetbrains.kotlin.plugin.parcelize
# navigationSafeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navSafeArgs" }
# jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composePlugin" } # Ensure 'composePlugin' version is defined if used like this
# openapiGenerator = { id = "org.openapi.generator", version.ref = "openapiGeneratorPlugin" }

[bundles]
# Example bundle
# compose = ["androidx.compose.ui", "androidx.compose.material3", "androidx.compose.ui.tooling.preview"]

# Xposed dependencies: these must be provided as local JARs or via a custom repo if not available in Maven Central.
