[versions]

agp = "8.14.2"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.1"

compileSdk = "36"
minSdk = "31"
targetSdk = "36"
jvmTarget = "21"

hilt = "2.56.2"

androidxCore = "1.16.0"
androidxLifecycle = "2.9.1"
androidxNavigation = "2.9.0"
androidxWork = "2.10.1"
androidxHiltWork = "1.2.0"
androidxViewBinding = "8.10.1"
androidxDataBinding = "8.10.1"

okhttp = "4.12.0"
retrofit = "3.0.0"
volley = "1.2.1"

jacksonKotlin = "2.19.0"
vertx = "5.0.0"
timber = "5.0.1"

googleMaterial = "1.12.0"
glide = "5.0.0-rc01"
easyPermissions = "3.0.0"

openApiGenerator = "7.4.0"

junit = "4.13.2"
androidxTestExtJunit = "1.2.1"
mockk = "1.14.2"

googleServicesPlugin = "4.4.1"
firebaseCrashlyticsPlugin = "2.9.9"
firebasePerfPlugin = "1.4.2"
dokkaPlugin = "1.9.20"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version = "1.7.1" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.10.1" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version = "1.10.1" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.9.1" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version = "1.0.1" } # NEW ENTRY

androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version = "1.1.0" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version = "1.2.0" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.8" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.4.0" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCore" }
androidx-vectordrawable-animated = { group = "androidx.vectordrawable", name = "vectordrawable-animated", version = "1.2.0" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version = "1.4.1" }

androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version = "2.7.1" }

androidx-viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "androidxViewBinding" }
androidx-databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "androidxDataBinding" }
androidx-databinding-adapters = { group = "androidx.databinding", name = "databinding-adapters", version = "8.10.1" }
androidx-databinding-library = { group = "com.android.databinding", name = "library", version.ref = "androidxDataBinding" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.06.00" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
jetbrains-compose-resources-android = { group = "org.jetbrains.compose.components", name = "components-resources-android", version = "1.8.1" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "androidxHiltWork" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHiltWork" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-script-runtime = { group = "org.jetbrains.kotlin", name = "kotlin-script-runtime", version.ref = "kotlin" }
kotlin-script-util = { group = "org.jetbrains.kotlin", name = "kotlin-script-util", version = "1.8.22" }
kotlin-scripting-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-jvm", version.ref = "kotlin" }
kotlin-scripting-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-compiler", version.ref = "kotlin" }
kotlin-scripting-dependencies = { group = "org.jetbrains.kotlin", name = "kotlin-scripting-dependencies", version.ref = "kotlin" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.10.2" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.8.1" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "33.15.0" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-messaging-ktx = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version = "3.0.0" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
grpc-kotlin-stub = { group = "io.grpc", name = "grpc-kotlin-stub", version = "1.4.3" }

google-android-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
easy-permissions = { group = "pub.devrel", name = "easypermissions", version.ref = "easyPermissions" }
agentweb = { group = "com.bytedance.ttgame", name = "agentweb", version = "4.1.22.1" }

jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jacksonKotlin" }