name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build with Gradle
        run: |
          ./gradlew build --no-daemon
          ./gradlew detekt ktlintCheck

      - name: Run tests
        run: |
          ./gradlew test
          ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.FlakyTest

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: app-release
          path: app/build/outputs/apk/release/
          retention-days: 7

      - name: Upload Build Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: |
            app/build/reports/
            build/reports/
          retention-days: 7

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            app/build/test-results/
            build/test-results/
          retention-days: 7
