name: Build and Publish

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

# Set the permissions at the workflow level
permissions:
  contents: read
  packages: write
  actions: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      packages: write # for actions/upload-artifact to upload artifacts
      actions: write # for gradle/wrapper-validation-action to validate Gradle Wrapper

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Fix Gradle Wrapper permissions
    - name: Make Gradlew executable
      run: chmod +x gradlew

    # Validate Gradle Wrapper
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v3

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    # Build the project
    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    # Run tests
    - name: Run tests
      run: ./gradlew test

    # Upload build artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: app-release
        path: app/build/outputs/apk/release/
        retention-days: 7

    # Upload build reports
    - name: Upload Build Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: |
          app/build/reports/
          build/reports/
        retention-days: 7

    # Upload test results
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/test-results/
          build/test-results/
        retention-days: 7
