name: Gradle Validation

on:
  push:
    branches: [ main, gradle-fixes ]
  pull_request:
    branches: [ main ]

jobs:
  validate-gradle:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for GitHub's dependency submission API

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Submit Gradle dependencies
        uses: gradle/actions/dependency-submission@v3
        with:
          gradle-version: wrapper
          build-scan-publish: true
          build-scan-terms-of-use-agreed: true
