name: Beta Release CI

on:
  push:
    tags:
      - 'v*beta*'
    branches:
      - beta
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

    # Optional: Distribute to Firebase App Distribution for beta testers
    # Uncomment and fill in app ID if you want to enable
    # - name: Decode and save Firebase service account key
    #   run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${{ github.workspace }}/serviceAccount.json"

    # - name: Install Firebase CLI
    #   run: npm install -g firebase-tools

    # - name: Distribute APK to Firebase App Distribution
    #   run: |
    #     firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}
    #     firebase appdistribution:distribute app/build/outputs/apk/debug/app-debug.apk \
    #       --app "your-firebase-app-id" \
    #       --token "${{ secrets.FIREBASE_TOKEN }}"
    #   env:
    #     GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccount.json
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
